[workspace]
members = [
    "kzg",
    "plookup",
    "fri",
    "sumcheck"
]


[patch.crates-io]
ark-std = { git = "https://github.com/arkworks-rs/std" }
pub-srs = { git =  "https://github.com/confuseSUN/srs" }