[workspace]
members = [
    "kzg",
    "plookup",
    "fri",
    "sumcheck",
    "sample_field",
    "poseidon",
    "ipa",
    "hash_to_curve",
]


[patch.crates-io]
ark-std = { git = "https://github.com/arkworks-rs/std" }
pub-srs = { git =  "https://github.com/confuseSUN/srs" }